name: Coverage
on:
  push:
    branches:
      - master
  pull_request:
env:
  RUSTFLAGS: "-D warnings"

jobs:
  get_msrv:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.rust_msrv.outputs.version }}
    steps:
    - uses: actions/checkout@v4
    - name: Get MSRV
      id: rust_msrv
      run: |
        RUST_MSRV="$(cat Cargo.toml | sed -n 's/rust-version *= *"\(.*\)"/\1/p')"
        echo "Found MSRV: $RUST_MSRV"
        echo "version=$RUST_MSRV" >> "$GITHUB_OUTPUT"

  coverage:
    needs: [get_msrv]
    runs-on: ubuntu-latest
    name: "Coverage"
    steps:
      - uses: actions/checkout@v4
      - name: Install LLVM
        run: |
          sudo apt-get update
          sudo apt-get install -y llvm lld
      - name: Install cargo-llvm-cov
        run: cargo install cargo-llvm-cov
      - name: Llvm version
        run: llvm-config --version
      - name: Clang version
        run: clang --version
      - name: "${{ needs.get_msrv.outputs.version }} with rustfmt, and wasm32"
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ needs.get_msrv.outputs.version }}
          target: wasm32-unknown-unknown
      - name: Set Default Toolchain
        run: rustup override set $ ${{ needs.get_msrv.outputs.version }}
      - uses: Swatinem/rust-cache@v2
      - name: Rust version
        run: rustc --version --verbose
      - name: Add rust-src component
        run: rustup component add rust-src --toolchain ${{ needs.get_msrv.outputs.version }}
      - name: Verify Rust Toolchain
        run: rustup show
      - name: Generate code coverage
        run: cargo +${{ needs.get_msrv.outputs.version }} llvm-cov --lcov --output-path llvm-cov-output.lcov
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        with:
          fail_ci_if_error: true
          files: ./llvm-cov-output.lcov
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true
